''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
'
' Example program:
'   MultiFunctionSyncAIAO_DigStart
'
' Category:
'   Synchronization
'
' Description:
'   This example demonstrates how to continuously acquire and generate
'   synchronized analog input and output, with an external digital start
'   trigger.
'
' Instructions for running:
'   1.  Select the physical channels corresponding to where your signals are
'       input and output on the DAQ device.
'   2.  Enter the minimum and maximum voltage ranges.
'       Note: For better accuracy try to match the ranges to the expected
'       voltage level of the measured or generated signals.
'   3.  Set the number of samples to acquire per channel.
'   4.  Set the rate of the acquisition and generation.
'       Note: The rate should be at least twice as fast as the maximum frequency
'       component of the signal being acquired.
'   5.  Set the physical channel for the external digital trigger.  The default
'       is PFI0.
'   6.  Set the type, frequency, and amplitude of the wave to be generated.
'       Note: This example requires two DMA channels to run.  If your hardware
'       does not support two DMA channels, you need to set the
'       AOChannel.DataTransferMechanism property for the analog output task to
'       use interrupts.
'
' Steps:
'   1.  Create analog input and output voltage channels for measurement and
'       acquisition.
'   2.  Set timing parameters for continuous generation and acquisition.  The
'       sample rate and number of samples are set to the same values for each
'       task.
'   3.  Configure start triggers that will synchronize both tasks by triggering
'       the output task from the AI Start Trigger.
'   4.  Create the signal to be generated by the output task.
'   5.  Create an AnalogSingleChannelWriter and associate it with the output
'       task by using the task's stream.  Call
'       AnalogSingleChannelWriter.WriteMultiSample to write the data.
'   6.  Call Task.Start() on each task to start the acquisition and generation.
'       Note: The output task must start before the input task because it is
'       waiting on the input task for the start trigger.
'   7.  Create an AnalogSingleChannelReader and associate it with the input task
'       by using the task's stream. Call
'       AnalogSingleChannelReader.BeginReadMultiSample to install a callback and
'       begin the asynchronous read operation.
'   8.  Inside the callback, call AnalogSingleChannelReader.EndReadMultiSample
'       to retrieve the data from the read.
'   9.  Call AnalogSingleChannelReader.BeginReadMultiSample again inside the
'       callback to perform another read.
'   10. Dispose the Task object to clean-up any resources associated with the
'       task.
'   11. Handle any DaqExceptions, if they occur.
'
' I/O Connections Overview:
'   Make sure your signal input terminals match the Physical Channel I/O
'   controls.
'
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

Imports System
Imports System.Drawing
Imports System.Collections
Imports System.ComponentModel
Imports System.Windows.Forms
Imports System.Data
Imports NationalInstruments
Imports NationalInstruments.DAQmx
Imports NationalInstruments.Analysis.SignalGeneration
Imports NationalInstruments.UI

Public Class MainForm
    Inherits System.Windows.Forms.Form
    Private inputTask As Task
    Private outputTask As Task
    Private reader As AnalogSingleChannelReader
    Private writer As AnalogSingleChannelWriter
    Private inputCallback As AsyncCallback

    Private runningTask As Task
    Private timingGroupBox As System.Windows.Forms.GroupBox
    Private rateLabel As System.Windows.Forms.Label
    Private WithEvents startButton As System.Windows.Forms.Button
    Private WithEvents stopButton As System.Windows.Forms.Button
    Private waveformTypeLabel As System.Windows.Forms.Label
    Private amplitudeLabel As System.Windows.Forms.Label
    Private waveformGroupBox As System.Windows.Forms.GroupBox
    Private waveformTypeComboBox As System.Windows.Forms.ComboBox
    Private triggerSourceLabel As System.Windows.Forms.Label
    Private triggerEdgeLabel As System.Windows.Forms.Label
    Private inputChannelComboBox As System.Windows.Forms.ComboBox
    Private inputChanLabel As System.Windows.Forms.Label
    Private inputMaxValLabel As System.Windows.Forms.Label
    Private inputMinValLabel As System.Windows.Forms.Label
    Private samplesLabel As System.Windows.Forms.Label
    Private outputMaxValLabel As System.Windows.Forms.Label
    Private outputMinValLabel As System.Windows.Forms.Label
    Private outputChanLabel As System.Windows.Forms.Label
    Private triggerEdgeComboBox As System.Windows.Forms.ComboBox
    Private triggerSourceTextBox As System.Windows.Forms.TextBox
    Private inputChanGroupBox As System.Windows.Forms.GroupBox
    Private outputChanGroupBox As System.Windows.Forms.GroupBox
    Private triggerGroupBox As System.Windows.Forms.GroupBox
    Private frequencyLabel As System.Windows.Forms.Label
    Private xAxis1 As NationalInstruments.UI.XAxis
    Private yAxis1 As NationalInstruments.UI.YAxis
    Private waveformPlot1 As NationalInstruments.UI.WaveformPlot
    Private outputWaveformGraph As NationalInstruments.UI.WindowsForms.WaveformGraph
    Private inputWaveformGraph As NationalInstruments.UI.WindowsForms.WaveformGraph
    Private waveformPlot2 As NationalInstruments.UI.WaveformPlot
    Private xAxis2 As NationalInstruments.UI.XAxis
    Private yAxis2 As NationalInstruments.UI.YAxis
    Private components As System.ComponentModel.Container = Nothing

    Public Sub New()
        MyBase.New()
        Application.EnableVisualStyles()
        Application.DoEvents()

        '
        ' Required for Windows Form Designer support
        '
        InitializeComponent()

        ' Initialize UI
        inputChannelComboBox.Items.AddRange(DaqSystem.Local.GetPhysicalChannels(PhysicalChannelTypes.AI, PhysicalChannelAccess.External))
        outputChannelComboBox.Items.AddRange(DaqSystem.Local.GetPhysicalChannels(PhysicalChannelTypes.AO, PhysicalChannelAccess.External))

        waveformTypeComboBox.SelectedIndex = 0
        triggerEdgeComboBox.SelectedIndex = 0
    End Sub 'New

    Protected Overloads Overrides Sub Dispose(ByVal disposing As Boolean)
        If disposing Then
            If Not (components Is Nothing) Then
                components.Dispose()
            End If
            If Not (inputTask Is Nothing) Then
                runningTask = Nothing
                inputTask.Dispose()
            End If
            If Not (outputTask Is Nothing) Then
                outputTask.Dispose()
            End If
        End If
        MyBase.Dispose(disposing)
    End Sub 'Dispose
    Private WithEvents inputMinValueNumericEdit As NationalInstruments.UI.WindowsForms.NumericEdit
    Private WithEvents inputMaxValueNumericEdit As NationalInstruments.UI.WindowsForms.NumericEdit
    Private WithEvents numberOfSamplesNumericEdit As NationalInstruments.UI.WindowsForms.NumericEdit
    Private WithEvents sampleRateNumericEdit As NationalInstruments.UI.WindowsForms.NumericEdit
    Private WithEvents outputMinValueNumericEdit As NationalInstruments.UI.WindowsForms.NumericEdit
    Private WithEvents outputMaxValueNumericEdit As NationalInstruments.UI.WindowsForms.NumericEdit
    Private WithEvents outputChannelComboBox As System.Windows.Forms.ComboBox
    Private WithEvents amplitudeNumericEdit As NationalInstruments.UI.WindowsForms.NumericEdit
    Private WithEvents frequencyNumericEdit As NationalInstruments.UI.WindowsForms.NumericEdit

    Private Sub InitializeComponent()
        Dim resources As New System.Resources.ResourceManager(GetType(MainForm))
        Me.inputChanGroupBox = New System.Windows.Forms.GroupBox
        Me.inputMinValueNumericEdit = New NationalInstruments.UI.WindowsForms.NumericEdit
        Me.inputMaxValueNumericEdit = New NationalInstruments.UI.WindowsForms.NumericEdit
        Me.inputChannelComboBox = New System.Windows.Forms.ComboBox
        Me.inputChanLabel = New System.Windows.Forms.Label
        Me.inputMaxValLabel = New System.Windows.Forms.Label
        Me.inputMinValLabel = New System.Windows.Forms.Label
        Me.timingGroupBox = New System.Windows.Forms.GroupBox
        Me.numberOfSamplesNumericEdit = New NationalInstruments.UI.WindowsForms.NumericEdit
        Me.sampleRateNumericEdit = New NationalInstruments.UI.WindowsForms.NumericEdit
        Me.samplesLabel = New System.Windows.Forms.Label
        Me.rateLabel = New System.Windows.Forms.Label
        Me.frequencyLabel = New System.Windows.Forms.Label
        Me.startButton = New System.Windows.Forms.Button
        Me.outputChanGroupBox = New System.Windows.Forms.GroupBox
        Me.outputMinValueNumericEdit = New NationalInstruments.UI.WindowsForms.NumericEdit
        Me.outputMaxValueNumericEdit = New NationalInstruments.UI.WindowsForms.NumericEdit
        Me.outputChannelComboBox = New System.Windows.Forms.ComboBox
        Me.outputMaxValLabel = New System.Windows.Forms.Label
        Me.outputMinValLabel = New System.Windows.Forms.Label
        Me.outputChanLabel = New System.Windows.Forms.Label
        Me.stopButton = New System.Windows.Forms.Button
        Me.waveformGroupBox = New System.Windows.Forms.GroupBox
        Me.amplitudeNumericEdit = New NationalInstruments.UI.WindowsForms.NumericEdit
        Me.frequencyNumericEdit = New NationalInstruments.UI.WindowsForms.NumericEdit
        Me.waveformTypeComboBox = New System.Windows.Forms.ComboBox
        Me.waveformTypeLabel = New System.Windows.Forms.Label
        Me.amplitudeLabel = New System.Windows.Forms.Label
        Me.triggerSourceLabel = New System.Windows.Forms.Label
        Me.triggerEdgeLabel = New System.Windows.Forms.Label
        Me.triggerEdgeComboBox = New System.Windows.Forms.ComboBox
        Me.triggerSourceTextBox = New System.Windows.Forms.TextBox
        Me.triggerGroupBox = New System.Windows.Forms.GroupBox
        Me.outputWaveformGraph = New NationalInstruments.UI.WindowsForms.WaveformGraph
        Me.waveformPlot1 = New NationalInstruments.UI.WaveformPlot
        Me.xAxis1 = New NationalInstruments.UI.XAxis
        Me.yAxis1 = New NationalInstruments.UI.YAxis
        Me.inputWaveformGraph = New NationalInstruments.UI.WindowsForms.WaveformGraph
        Me.waveformPlot2 = New NationalInstruments.UI.WaveformPlot
        Me.xAxis2 = New NationalInstruments.UI.XAxis
        Me.yAxis2 = New NationalInstruments.UI.YAxis
        Me.inputChanGroupBox.SuspendLayout()
        CType(Me.inputMinValueNumericEdit, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.inputMaxValueNumericEdit, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.timingGroupBox.SuspendLayout()
        CType(Me.numberOfSamplesNumericEdit, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.sampleRateNumericEdit, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.outputChanGroupBox.SuspendLayout()
        CType(Me.outputMinValueNumericEdit, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.outputMaxValueNumericEdit, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.waveformGroupBox.SuspendLayout()
        CType(Me.amplitudeNumericEdit, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.frequencyNumericEdit, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.triggerGroupBox.SuspendLayout()
        CType(Me.outputWaveformGraph, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.inputWaveformGraph, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.SuspendLayout()
        '
        'inputChanGroupBox
        '
        Me.inputChanGroupBox.Controls.Add(Me.inputMinValueNumericEdit)
        Me.inputChanGroupBox.Controls.Add(Me.inputMaxValueNumericEdit)
        Me.inputChanGroupBox.Controls.Add(Me.inputChannelComboBox)
        Me.inputChanGroupBox.Controls.Add(Me.inputChanLabel)
        Me.inputChanGroupBox.Controls.Add(Me.inputMaxValLabel)
        Me.inputChanGroupBox.Controls.Add(Me.inputMinValLabel)
        Me.inputChanGroupBox.FlatStyle = System.Windows.Forms.FlatStyle.System
        Me.inputChanGroupBox.Location = New System.Drawing.Point(8, 8)
        Me.inputChanGroupBox.Name = "inputChanGroupBox"
        Me.inputChanGroupBox.Size = New System.Drawing.Size(280, 112)
        Me.inputChanGroupBox.TabIndex = 2
        Me.inputChanGroupBox.TabStop = False
        Me.inputChanGroupBox.Text = "Channel Parameters - Input"
        '
        'inputMinValueNumericEdit
        '
        Me.inputMinValueNumericEdit.Location = New System.Drawing.Point(152, 79)
        Me.inputMinValueNumericEdit.Name = "inputMinValueNumericEdit"
        Me.inputMinValueNumericEdit.OutOfRangeMode = NationalInstruments.UI.NumericOutOfRangeMode.CoerceToRange
        Me.inputMinValueNumericEdit.Range = New NationalInstruments.UI.Range(-10, 0)
        Me.inputMinValueNumericEdit.Size = New System.Drawing.Size(112, 20)
        Me.inputMinValueNumericEdit.TabIndex = 2
        Me.inputMinValueNumericEdit.Value = -10
        '
        'inputMaxValueNumericEdit
        '
        Me.inputMaxValueNumericEdit.Location = New System.Drawing.Point(152, 52)
        Me.inputMaxValueNumericEdit.Name = "inputMaxValueNumericEdit"
        Me.inputMaxValueNumericEdit.OutOfRangeMode = NationalInstruments.UI.NumericOutOfRangeMode.CoerceToRange
        Me.inputMaxValueNumericEdit.Range = New NationalInstruments.UI.Range(0, 10)
        Me.inputMaxValueNumericEdit.Size = New System.Drawing.Size(112, 20)
        Me.inputMaxValueNumericEdit.TabIndex = 1
        Me.inputMaxValueNumericEdit.Value = 10
        '
        'inputChannelComboBox
        '
        Me.inputChannelComboBox.Location = New System.Drawing.Point(152, 24)
        Me.inputChannelComboBox.Name = "inputChannelComboBox"
        Me.inputChannelComboBox.Size = New System.Drawing.Size(112, 21)
        Me.inputChannelComboBox.TabIndex = 0
        Me.inputChannelComboBox.Text = "Dev1/ai0"
        '
        'inputChanLabel
        '
        Me.inputChanLabel.FlatStyle = System.Windows.Forms.FlatStyle.System
        Me.inputChanLabel.Location = New System.Drawing.Point(16, 26)
        Me.inputChanLabel.Name = "inputChanLabel"
        Me.inputChanLabel.Size = New System.Drawing.Size(96, 16)
        Me.inputChanLabel.TabIndex = 0
        Me.inputChanLabel.Text = "Input Channel:"
        '
        'inputMaxValLabel
        '
        Me.inputMaxValLabel.FlatStyle = System.Windows.Forms.FlatStyle.System
        Me.inputMaxValLabel.Location = New System.Drawing.Point(16, 54)
        Me.inputMaxValLabel.Name = "inputMaxValLabel"
        Me.inputMaxValLabel.Size = New System.Drawing.Size(96, 16)
        Me.inputMaxValLabel.TabIndex = 2
        Me.inputMaxValLabel.Text = "Maximum Value:"
        '
        'inputMinValLabel
        '
        Me.inputMinValLabel.FlatStyle = System.Windows.Forms.FlatStyle.System
        Me.inputMinValLabel.Location = New System.Drawing.Point(16, 82)
        Me.inputMinValLabel.Name = "inputMinValLabel"
        Me.inputMinValLabel.Size = New System.Drawing.Size(96, 16)
        Me.inputMinValLabel.TabIndex = 4
        Me.inputMinValLabel.Text = "Minimum Value:"
        '
        'timingGroupBox
        '
        Me.timingGroupBox.Controls.Add(Me.numberOfSamplesNumericEdit)
        Me.timingGroupBox.Controls.Add(Me.sampleRateNumericEdit)
        Me.timingGroupBox.Controls.Add(Me.samplesLabel)
        Me.timingGroupBox.Controls.Add(Me.rateLabel)
        Me.timingGroupBox.FlatStyle = System.Windows.Forms.FlatStyle.System
        Me.timingGroupBox.Location = New System.Drawing.Point(8, 248)
        Me.timingGroupBox.Name = "timingGroupBox"
        Me.timingGroupBox.Size = New System.Drawing.Size(280, 88)
        Me.timingGroupBox.TabIndex = 4
        Me.timingGroupBox.TabStop = False
        Me.timingGroupBox.Text = "Timing Parameters"
        '
        'numberOfSamplesNumericEdit
        '
        Me.numberOfSamplesNumericEdit.Location = New System.Drawing.Point(152, 48)
        Me.numberOfSamplesNumericEdit.Name = "numberOfSamplesNumericEdit"
        Me.numberOfSamplesNumericEdit.OutOfRangeMode = NationalInstruments.UI.NumericOutOfRangeMode.CoerceToRange
        Me.numberOfSamplesNumericEdit.Range = New NationalInstruments.UI.Range(1, 100000)
        Me.numberOfSamplesNumericEdit.Size = New System.Drawing.Size(112, 20)
        Me.numberOfSamplesNumericEdit.TabIndex = 1
        Me.numberOfSamplesNumericEdit.Value = 1000
        '
        'sampleRateNumericEdit
        '
        Me.sampleRateNumericEdit.Location = New System.Drawing.Point(152, 21)
        Me.sampleRateNumericEdit.Name = "sampleRateNumericEdit"
        Me.sampleRateNumericEdit.OutOfRangeMode = NationalInstruments.UI.NumericOutOfRangeMode.CoerceToRange
        Me.sampleRateNumericEdit.Range = New NationalInstruments.UI.Range(0, 100000)
        Me.sampleRateNumericEdit.Size = New System.Drawing.Size(112, 20)
        Me.sampleRateNumericEdit.TabIndex = 0
        Me.sampleRateNumericEdit.Value = 1000
        '
        'samplesLabel
        '
        Me.samplesLabel.FlatStyle = System.Windows.Forms.FlatStyle.System
        Me.samplesLabel.Location = New System.Drawing.Point(16, 51)
        Me.samplesLabel.Name = "samplesLabel"
        Me.samplesLabel.Size = New System.Drawing.Size(120, 15)
        Me.samplesLabel.TabIndex = 4
        Me.samplesLabel.Text = "Number Of Samples:"
        '
        'rateLabel
        '
        Me.rateLabel.FlatStyle = System.Windows.Forms.FlatStyle.System
        Me.rateLabel.Location = New System.Drawing.Point(16, 23)
        Me.rateLabel.Name = "rateLabel"
        Me.rateLabel.Size = New System.Drawing.Size(96, 16)
        Me.rateLabel.TabIndex = 0
        Me.rateLabel.Text = "Sample Rate (Hz):"
        '
        'frequencyLabel
        '
        Me.frequencyLabel.FlatStyle = System.Windows.Forms.FlatStyle.System
        Me.frequencyLabel.Location = New System.Drawing.Point(16, 54)
        Me.frequencyLabel.Name = "frequencyLabel"
        Me.frequencyLabel.Size = New System.Drawing.Size(120, 16)
        Me.frequencyLabel.TabIndex = 2
        Me.frequencyLabel.Text = "Frequency  (Hz):"
        '
        'startButton
        '
        Me.startButton.FlatStyle = System.Windows.Forms.FlatStyle.System
        Me.startButton.Location = New System.Drawing.Point(400, 496)
        Me.startButton.Name = "startButton"
        Me.startButton.Size = New System.Drawing.Size(88, 32)
        Me.startButton.TabIndex = 0
        Me.startButton.Text = "Start"
        '
        'outputChanGroupBox
        '
        Me.outputChanGroupBox.Controls.Add(Me.outputMinValueNumericEdit)
        Me.outputChanGroupBox.Controls.Add(Me.outputMaxValueNumericEdit)
        Me.outputChanGroupBox.Controls.Add(Me.outputChannelComboBox)
        Me.outputChanGroupBox.Controls.Add(Me.outputMaxValLabel)
        Me.outputChanGroupBox.Controls.Add(Me.outputMinValLabel)
        Me.outputChanGroupBox.Controls.Add(Me.outputChanLabel)
        Me.outputChanGroupBox.FlatStyle = System.Windows.Forms.FlatStyle.System
        Me.outputChanGroupBox.Location = New System.Drawing.Point(8, 128)
        Me.outputChanGroupBox.Name = "outputChanGroupBox"
        Me.outputChanGroupBox.Size = New System.Drawing.Size(280, 112)
        Me.outputChanGroupBox.TabIndex = 3
        Me.outputChanGroupBox.TabStop = False
        Me.outputChanGroupBox.Text = "Channel Parameters - Output"
        '
        'outputMinValueNumericEdit
        '
        Me.outputMinValueNumericEdit.Location = New System.Drawing.Point(152, 79)
        Me.outputMinValueNumericEdit.Name = "outputMinValueNumericEdit"
        Me.outputMinValueNumericEdit.OutOfRangeMode = NationalInstruments.UI.NumericOutOfRangeMode.CoerceToRange
        Me.outputMinValueNumericEdit.Range = New NationalInstruments.UI.Range(-10, 0)
        Me.outputMinValueNumericEdit.Size = New System.Drawing.Size(112, 20)
        Me.outputMinValueNumericEdit.TabIndex = 2
        Me.outputMinValueNumericEdit.Value = -10
        '
        'outputMaxValueNumericEdit
        '
        Me.outputMaxValueNumericEdit.Location = New System.Drawing.Point(152, 52)
        Me.outputMaxValueNumericEdit.Name = "outputMaxValueNumericEdit"
        Me.outputMaxValueNumericEdit.OutOfRangeMode = NationalInstruments.UI.NumericOutOfRangeMode.CoerceToRange
        Me.outputMaxValueNumericEdit.Range = New NationalInstruments.UI.Range(0, 10)
        Me.outputMaxValueNumericEdit.Size = New System.Drawing.Size(112, 20)
        Me.outputMaxValueNumericEdit.TabIndex = 1
        Me.outputMaxValueNumericEdit.Value = 10
        '
        'outputChannelComboBox
        '
        Me.outputChannelComboBox.Location = New System.Drawing.Point(152, 24)
        Me.outputChannelComboBox.Name = "outputChannelComboBox"
        Me.outputChannelComboBox.Size = New System.Drawing.Size(112, 21)
        Me.outputChannelComboBox.TabIndex = 0
        Me.outputChannelComboBox.Text = "Dev1/ao0"
        '
        'outputMaxValLabel
        '
        Me.outputMaxValLabel.FlatStyle = System.Windows.Forms.FlatStyle.System
        Me.outputMaxValLabel.Location = New System.Drawing.Point(16, 54)
        Me.outputMaxValLabel.Name = "outputMaxValLabel"
        Me.outputMaxValLabel.Size = New System.Drawing.Size(96, 16)
        Me.outputMaxValLabel.TabIndex = 2
        Me.outputMaxValLabel.Text = "Maximum Value:"
        '
        'outputMinValLabel
        '
        Me.outputMinValLabel.FlatStyle = System.Windows.Forms.FlatStyle.System
        Me.outputMinValLabel.Location = New System.Drawing.Point(16, 81)
        Me.outputMinValLabel.Name = "outputMinValLabel"
        Me.outputMinValLabel.Size = New System.Drawing.Size(96, 16)
        Me.outputMinValLabel.TabIndex = 4
        Me.outputMinValLabel.Text = "Minimum Value:"
        '
        'outputChanLabel
        '
        Me.outputChanLabel.FlatStyle = System.Windows.Forms.FlatStyle.System
        Me.outputChanLabel.Location = New System.Drawing.Point(16, 26)
        Me.outputChanLabel.Name = "outputChanLabel"
        Me.outputChanLabel.Size = New System.Drawing.Size(96, 16)
        Me.outputChanLabel.TabIndex = 0
        Me.outputChanLabel.Text = "Output Channel:"
        '
        'stopButton
        '
        Me.stopButton.Enabled = False
        Me.stopButton.FlatStyle = System.Windows.Forms.FlatStyle.System
        Me.stopButton.Location = New System.Drawing.Point(536, 496)
        Me.stopButton.Name = "stopButton"
        Me.stopButton.Size = New System.Drawing.Size(88, 32)
        Me.stopButton.TabIndex = 1
        Me.stopButton.Text = "Stop"
        '
        'waveformGroupBox
        '
        Me.waveformGroupBox.Controls.Add(Me.amplitudeNumericEdit)
        Me.waveformGroupBox.Controls.Add(Me.frequencyNumericEdit)
        Me.waveformGroupBox.Controls.Add(Me.waveformTypeComboBox)
        Me.waveformGroupBox.Controls.Add(Me.waveformTypeLabel)
        Me.waveformGroupBox.Controls.Add(Me.amplitudeLabel)
        Me.waveformGroupBox.Controls.Add(Me.frequencyLabel)
        Me.waveformGroupBox.FlatStyle = System.Windows.Forms.FlatStyle.System
        Me.waveformGroupBox.Location = New System.Drawing.Point(8, 432)
        Me.waveformGroupBox.Name = "waveformGroupBox"
        Me.waveformGroupBox.Size = New System.Drawing.Size(280, 112)
        Me.waveformGroupBox.TabIndex = 6
        Me.waveformGroupBox.TabStop = False
        Me.waveformGroupBox.Text = "Waveform Parameters"
        '
        'amplitudeNumericEdit
        '
        Me.amplitudeNumericEdit.Location = New System.Drawing.Point(152, 79)
        Me.amplitudeNumericEdit.Name = "amplitudeNumericEdit"
        Me.amplitudeNumericEdit.OutOfRangeMode = NationalInstruments.UI.NumericOutOfRangeMode.CoerceToRange
        Me.amplitudeNumericEdit.Range = New NationalInstruments.UI.Range(-10, 10)
        Me.amplitudeNumericEdit.Size = New System.Drawing.Size(112, 20)
        Me.amplitudeNumericEdit.TabIndex = 3
        Me.amplitudeNumericEdit.Value = 1
        '
        'frequencyNumericEdit
        '
        Me.frequencyNumericEdit.Location = New System.Drawing.Point(152, 52)
        Me.frequencyNumericEdit.Name = "frequencyNumericEdit"
        Me.frequencyNumericEdit.OutOfRangeMode = NationalInstruments.UI.NumericOutOfRangeMode.CoerceToRange
        Me.frequencyNumericEdit.Range = New NationalInstruments.UI.Range(0, 100000)
        Me.frequencyNumericEdit.Size = New System.Drawing.Size(112, 20)
        Me.frequencyNumericEdit.TabIndex = 2
        Me.frequencyNumericEdit.Value = 10
        '
        'waveformTypeComboBox
        '
        Me.waveformTypeComboBox.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList
        Me.waveformTypeComboBox.Items.AddRange(New Object() {"Sine Wave", "Square Wave", "Triangle Wave", "Sawtooth Wave"})
        Me.waveformTypeComboBox.Location = New System.Drawing.Point(152, 24)
        Me.waveformTypeComboBox.Name = "waveformTypeComboBox"
        Me.waveformTypeComboBox.Size = New System.Drawing.Size(112, 21)
        Me.waveformTypeComboBox.TabIndex = 0
        '
        'waveformTypeLabel
        '
        Me.waveformTypeLabel.FlatStyle = System.Windows.Forms.FlatStyle.System
        Me.waveformTypeLabel.Location = New System.Drawing.Point(16, 26)
        Me.waveformTypeLabel.Name = "waveformTypeLabel"
        Me.waveformTypeLabel.Size = New System.Drawing.Size(96, 16)
        Me.waveformTypeLabel.TabIndex = 0
        Me.waveformTypeLabel.Text = "Waveform Type:"
        '
        'amplitudeLabel
        '
        Me.amplitudeLabel.FlatStyle = System.Windows.Forms.FlatStyle.System
        Me.amplitudeLabel.Location = New System.Drawing.Point(16, 81)
        Me.amplitudeLabel.Name = "amplitudeLabel"
        Me.amplitudeLabel.Size = New System.Drawing.Size(96, 16)
        Me.amplitudeLabel.TabIndex = 2
        Me.amplitudeLabel.Text = "Amplitude:"
        '
        'triggerSourceLabel
        '
        Me.triggerSourceLabel.FlatStyle = System.Windows.Forms.FlatStyle.System
        Me.triggerSourceLabel.Location = New System.Drawing.Point(16, 26)
        Me.triggerSourceLabel.Name = "triggerSourceLabel"
        Me.triggerSourceLabel.Size = New System.Drawing.Size(120, 16)
        Me.triggerSourceLabel.TabIndex = 0
        Me.triggerSourceLabel.Text = "Digital Trigger Source:"
        '
        'triggerEdgeLabel
        '
        Me.triggerEdgeLabel.FlatStyle = System.Windows.Forms.FlatStyle.System
        Me.triggerEdgeLabel.Location = New System.Drawing.Point(16, 54)
        Me.triggerEdgeLabel.Name = "triggerEdgeLabel"
        Me.triggerEdgeLabel.Size = New System.Drawing.Size(96, 16)
        Me.triggerEdgeLabel.TabIndex = 2
        Me.triggerEdgeLabel.Text = "Trigger Edge:"
        '
        'triggerEdgeComboBox
        '
        Me.triggerEdgeComboBox.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList
        Me.triggerEdgeComboBox.Items.AddRange(New Object() {"Rising", "Falling"})
        Me.triggerEdgeComboBox.Location = New System.Drawing.Point(152, 52)
        Me.triggerEdgeComboBox.Name = "triggerEdgeComboBox"
        Me.triggerEdgeComboBox.Size = New System.Drawing.Size(112, 21)
        Me.triggerEdgeComboBox.TabIndex = 1
        '
        'triggerSourceTextBox
        '
        Me.triggerSourceTextBox.Location = New System.Drawing.Point(152, 24)
        Me.triggerSourceTextBox.Name = "triggerSourceTextBox"
        Me.triggerSourceTextBox.Size = New System.Drawing.Size(112, 20)
        Me.triggerSourceTextBox.TabIndex = 0
        Me.triggerSourceTextBox.Text = "/Dev1/PFI0"
        '
        'triggerGroupBox
        '
        Me.triggerGroupBox.Controls.Add(Me.triggerEdgeLabel)
        Me.triggerGroupBox.Controls.Add(Me.triggerSourceTextBox)
        Me.triggerGroupBox.Controls.Add(Me.triggerSourceLabel)
        Me.triggerGroupBox.Controls.Add(Me.triggerEdgeComboBox)
        Me.triggerGroupBox.FlatStyle = System.Windows.Forms.FlatStyle.System
        Me.triggerGroupBox.Location = New System.Drawing.Point(8, 344)
        Me.triggerGroupBox.Name = "triggerGroupBox"
        Me.triggerGroupBox.Size = New System.Drawing.Size(280, 80)
        Me.triggerGroupBox.TabIndex = 5
        Me.triggerGroupBox.TabStop = False
        Me.triggerGroupBox.Text = "Trigger Parameters"
        '
        'outputWaveformGraph
        '
        Me.outputWaveformGraph.Caption = "Generated Waveform"
        Me.outputWaveformGraph.Location = New System.Drawing.Point(320, 24)
        Me.outputWaveformGraph.Name = "outputWaveformGraph"
        Me.outputWaveformGraph.Plots.AddRange(New NationalInstruments.UI.WaveformPlot() {Me.waveformPlot1})
        Me.outputWaveformGraph.Size = New System.Drawing.Size(392, 224)
        Me.outputWaveformGraph.TabIndex = 7
        Me.outputWaveformGraph.TabStop = False
        Me.outputWaveformGraph.XAxes.AddRange(New NationalInstruments.UI.XAxis() {Me.xAxis1})
        Me.outputWaveformGraph.YAxes.AddRange(New NationalInstruments.UI.YAxis() {Me.yAxis1})
        '
        'waveformPlot1
        '
        Me.waveformPlot1.XAxis = Me.xAxis1
        Me.waveformPlot1.YAxis = Me.yAxis1
        '
        'xAxis1
        '
        Me.xAxis1.Caption = "Number Of Samples"
        '
        'yAxis1
        '
        Me.yAxis1.Caption = "Amplitude"
        Me.yAxis1.Mode = NationalInstruments.UI.AxisMode.AutoScaleExact
        '
        'inputWaveformGraph
        '
        Me.inputWaveformGraph.Caption = "Waveform On Input Channel"
        Me.inputWaveformGraph.Location = New System.Drawing.Point(320, 264)
        Me.inputWaveformGraph.Name = "inputWaveformGraph"
        Me.inputWaveformGraph.Plots.AddRange(New NationalInstruments.UI.WaveformPlot() {Me.waveformPlot2})
        Me.inputWaveformGraph.Size = New System.Drawing.Size(392, 224)
        Me.inputWaveformGraph.TabIndex = 7
        Me.inputWaveformGraph.TabStop = False
        Me.inputWaveformGraph.XAxes.AddRange(New NationalInstruments.UI.XAxis() {Me.xAxis2})
        Me.inputWaveformGraph.YAxes.AddRange(New NationalInstruments.UI.YAxis() {Me.yAxis2})
        '
        'waveformPlot2
        '
        Me.waveformPlot2.XAxis = Me.xAxis2
        Me.waveformPlot2.YAxis = Me.yAxis2
        '
        'xAxis2
        '
        Me.xAxis2.Caption = "Number Of Samples"
        '
        'yAxis2
        '
        Me.yAxis2.Caption = "Amplitude"
        Me.yAxis2.Mode = NationalInstruments.UI.AxisMode.AutoScaleExact
        '
        'MainForm
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(96.0!, 96.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi
        Me.ClientSize = New System.Drawing.Size(722, 552)
        Me.Controls.Add(Me.outputWaveformGraph)
        Me.Controls.Add(Me.startButton)
        Me.Controls.Add(Me.timingGroupBox)
        Me.Controls.Add(Me.outputChanGroupBox)
        Me.Controls.Add(Me.stopButton)
        Me.Controls.Add(Me.waveformGroupBox)
        Me.Controls.Add(Me.triggerGroupBox)
        Me.Controls.Add(Me.inputChanGroupBox)
        Me.Controls.Add(Me.inputWaveformGraph)
        Me.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog
        Me.Icon = CType(resources.GetObject("$this.Icon"), System.Drawing.Icon)
        Me.MaximizeBox = False
        Me.Name = "MainForm"
        Me.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen
        Me.Text = "Synchronize AI and AO using a Digital Trigger"
        Me.inputChanGroupBox.ResumeLayout(False)
        CType(Me.inputMinValueNumericEdit, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.inputMaxValueNumericEdit, System.ComponentModel.ISupportInitialize).EndInit()
        Me.timingGroupBox.ResumeLayout(False)
        CType(Me.numberOfSamplesNumericEdit, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.sampleRateNumericEdit, System.ComponentModel.ISupportInitialize).EndInit()
        Me.outputChanGroupBox.ResumeLayout(False)
        CType(Me.outputMinValueNumericEdit, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.outputMaxValueNumericEdit, System.ComponentModel.ISupportInitialize).EndInit()
        Me.waveformGroupBox.ResumeLayout(False)
        CType(Me.amplitudeNumericEdit, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.frequencyNumericEdit, System.ComponentModel.ISupportInitialize).EndInit()
        Me.triggerGroupBox.ResumeLayout(False)
        CType(Me.outputWaveformGraph, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.inputWaveformGraph, System.ComponentModel.ISupportInitialize).EndInit()
        Me.ResumeLayout(False)

    End Sub 'InitializeComponent

    Private Sub startButton_Click(ByVal sender As Object, ByVal e As System.EventArgs) Handles startButton.Click
        ' Change the mouse to an hourglass for the duration of this function.
        System.Windows.Forms.Cursor.Current = System.Windows.Forms.Cursors.WaitCursor
        inputWaveformGraph.ClearData()
        outputWaveformGraph.ClearData()

        ' Read UI selections
        Dim triggerEdge As DigitalEdgeStartTriggerEdge
        If triggerEdgeComboBox.SelectedIndex = 0 Then
            triggerEdge = DigitalEdgeStartTriggerEdge.Rising
        Else
            triggerEdge = DigitalEdgeStartTriggerEdge.Falling
        End If

        Dim fgen As SignalGenerator
        Select Case waveformTypeComboBox.SelectedIndex
            Case 0
                fgen = New SignalGenerator(sampleRateNumericEdit.Value, Convert.ToInt32(numberOfSamplesNumericEdit.Value), New SineSignal(frequencyNumericEdit.Value, amplitudeNumericEdit.Value))
            Case 1
                fgen = New SignalGenerator(sampleRateNumericEdit.Value, Convert.ToInt32(numberOfSamplesNumericEdit.Value), New SquareSignal(frequencyNumericEdit.Value, amplitudeNumericEdit.Value))
            Case 2
                fgen = New SignalGenerator(sampleRateNumericEdit.Value, Convert.ToInt32(numberOfSamplesNumericEdit.Value), New TriangleSignal(frequencyNumericEdit.Value, amplitudeNumericEdit.Value))
            Case 3
                fgen = New SignalGenerator(sampleRateNumericEdit.Value, Convert.ToInt32(numberOfSamplesNumericEdit.Value), New SawtoothSignal(frequencyNumericEdit.Value, amplitudeNumericEdit.Value))
            Case Else
                fgen = New SignalGenerator(sampleRateNumericEdit.Value, Convert.ToInt32(numberOfSamplesNumericEdit.Value), New SineSignal(frequencyNumericEdit.Value, amplitudeNumericEdit.Value))
        End Select

        Try
            ' Create the input and output tasks
            inputTask = New Task("inputTask")
            outputTask = New Task("outputTask")

            ' Configure both tasks with the values selected on the UI.
            inputTask.AIChannels.CreateVoltageChannel(inputChannelComboBox.Text, "", AITerminalConfiguration.Differential, inputMinValueNumericEdit.Value, inputMaxValueNumericEdit.Value, AIVoltageUnits.Volts)

            outputTask.AOChannels.CreateVoltageChannel(outputChannelComboBox.Text, "", outputMinValueNumericEdit.Value, outputMaxValueNumericEdit.Value, AOVoltageUnits.Volts)

            ' Set up the timing
            inputTask.Timing.ConfigureSampleClock("", sampleRateNumericEdit.Value, SampleClockActiveEdge.Rising, SampleQuantityMode.ContinuousSamples, Convert.ToInt32(numberOfSamplesNumericEdit.Value))

            outputTask.Timing.ConfigureSampleClock("", sampleRateNumericEdit.Value, SampleClockActiveEdge.Rising, SampleQuantityMode.ContinuousSamples, Convert.ToInt32(numberOfSamplesNumericEdit.Value))

            ' Set up the start trigger for the input task
            inputTask.Triggers.StartTrigger.ConfigureDigitalEdgeTrigger(triggerSourceTextBox.Text, triggerEdge)

            ' Set up "Dev1/ai/startTrigger" as the trigger source for the output task
            Dim deviceName As String = inputChannelComboBox.Text.Split("/"c)(0)
            Dim terminalNameBase As String = "/" + deviceName + "/"
            outputTask.Triggers.StartTrigger.ConfigureDigitalEdgeTrigger(terminalNameBase + "ai/StartTrigger", triggerEdge)

            ' Verify the tasks
            inputTask.Control(TaskAction.Verify)
            outputTask.Control(TaskAction.Verify)

            ' Write data to the output channel
            writer = New AnalogSingleChannelWriter(outputTask.Stream)
            Dim data As Double() = fgen.Generate()
            writer.WriteMultiSample(False, data)
            outputWaveformGraph.PlotY(data)

            ' Start the tasks and disable the UI
            StartTasks()

            ' Start reading as well
            inputCallback = New AsyncCallback(AddressOf InputRead)
            reader = New AnalogSingleChannelReader(inputTask.Stream)
            reader.SynchronizeCallbacks = True
            reader.BeginReadMultiSample(Convert.ToInt32(numberOfSamplesNumericEdit.Value), inputCallback, inputTask)
        Catch ex As Exception
            ' Stop the tasks and enable the UI
            StopTask()
            MessageBox.Show(ex.Message)
        End Try
    End Sub 'startButton_Click

    ' This callback is invoked everytime a Read completes
    Private Sub InputRead(ByVal ar As IAsyncResult)
        Try
            If (Not (runningTask Is Nothing)) AndAlso runningTask Is ar.AsyncState Then
                ' Read the data
                Dim data As Double() = reader.EndReadMultiSample(ar)
                inputWaveformGraph.PlotYAppend(data)

                ' Set up next callback
                reader.BeginReadMultiSample(Convert.ToInt32(numberOfSamplesNumericEdit.Value), inputCallback, inputTask)
            End If
        Catch ex As Exception
            StopTask()
            MessageBox.Show(ex.Message)
        End Try
    End Sub 'InputRead

    Private Sub stopButton_Click(ByVal sender As Object, ByVal e As System.EventArgs) Handles stopButton.Click
        StopTask()
    End Sub 'stopButton_Click

    Private Sub StartTasks()
        If runningTask Is Nothing Then
            ' Change state
            runningTask = inputTask

            ' Fix UI
            inputChannelComboBox.Enabled = False
            inputMinValueNumericEdit.Enabled = False
            inputMaxValueNumericEdit.Enabled = False

            outputChannelComboBox.Enabled = False
            outputChannelComboBox.Enabled = False
            outputChannelComboBox.Enabled = False
            outputMaxValueNumericEdit.Enabled = False
            outputMinValueNumericEdit.Enabled = False

            sampleRateNumericEdit.Enabled = False
            frequencyNumericEdit.Enabled = False
            numberOfSamplesNumericEdit.Enabled = False

            waveformTypeComboBox.Enabled = False
            amplitudeNumericEdit.Enabled = False
            triggerSourceTextBox.Enabled = False
            triggerEdgeComboBox.Enabled = False

            startButton.Enabled = False
            stopButton.Enabled = True
            outputTask.Start()
            inputTask.Start()
        End If
    End Sub 'StartTasks

    Private Sub StopTask()
        ' Change state
        runningTask = Nothing

        inputChannelComboBox.Enabled = True
        inputMinValueNumericEdit.Enabled = True
        inputMaxValueNumericEdit.Enabled = True

        outputChannelComboBox.Enabled = True
        outputChannelComboBox.Enabled = True
        outputChannelComboBox.Enabled = True
        outputMaxValueNumericEdit.Enabled = True
        outputMinValueNumericEdit.Enabled = True

        sampleRateNumericEdit.Enabled = True
        frequencyNumericEdit.Enabled = True
        numberOfSamplesNumericEdit.Enabled = True

        waveformTypeComboBox.Enabled = True
        amplitudeNumericEdit.Enabled = True
        triggerSourceTextBox.Enabled = True
        triggerEdgeComboBox.Enabled = True
        startButton.Enabled = True
        stopButton.Enabled = False

        ' Stop tasks
        inputTask.Stop()
        outputTask.Stop()

        inputTask.Dispose()
        outputTask.Dispose()
    End Sub 'StopTask
End Class 'MainForm 
