'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
'
' Example program:
'   MultiFunctionSyncAIAO
'
' Category:
'   Synchronization
'
' Description:
'   This example demonstrates how to continuously acquire and generate
'   synchronized analog input and output, started by an external digital start
'   trigger.
'
' Instructions for running:
'   1.  Select the physical channels corresponding to where your signals are
'       input and output on the DAQ device.
'   2.  Enter the minimum and maximum voltage ranges.Note: For better accuracy
'       try to match the ranges to the expected voltage level of the measured or
'       generated signals.
'   3.  Set the number of samples to acquire per channel.
'   4.  Set the rate of the acquisition and generation.Note: The rate should be
'       at least twice as fast as the maximum frequency component of the signal
'       being acquired.
'   5.  Set the physical channel for the external digital trigger.  The default
'       is PFI0.
'   6.  Set the type, frequency, and amplitude of the wave to be generated.Note:
'       This example requires two DMA channels to run.  If your hardware does
'       not support two DMA channels, you need to set the
'       AOChannel.DataTransferMechanism property for the analog output task to
'       use interrupts.
'
' Steps:
'   1.  Create analog input and output voltage channels for measurement and
'       acquisition.
'   2.  Set timing parameters for continuous generation and acquisition.  The
'       sample rate and number of samples are set to the same values for each
'       task.
'   3.  Configure start triggers that will synchronize both tasks by triggering
'       the output task from the AI Start Trigger.
'   4.  Create the signal to be generated by the output task.
'   5.  Create an AnalogSingleChannelWriter and associate it with the output
'       task by using the task's stream.  Call
'       AnalogSingleChannelWriter.WriteMultiSample to write the data.
'   6.  Call Task.Start() on each task to start the acquisition and
'       generation.Note: The output task must start before the input task
'       because it is waiting on the input task for the start trigger.
'   7.  Create an AnalogSingleChannelReader and associate it with the input task
'       by using the task's stream. Call
'       AnalogSingleChannelReader.BeginReadMultiSample to install a callback and
'       begin the asynchronous read operation.
'   8.  Inside the callback, call AnalogSingleChannelReader.EndReadMultiSample
'       to retrieve the data from the read.
'   9.  Call AnalogSingleChannelReader.BeginReadMultiSample again inside the
'       callback to perform another read operation.
'   10. Dispose the Task object to clean-up any resources associated with the
'       task.
'   11. Handle any DaqExceptions, if they occur.
'
'   Note: This example sets SynchronizeCallback to true. If SynchronizeCallback
'   is set to false, then you must give special consideration to safely dispose
'   the task and to update the UI from the callback. If SynchronizeCallback is
'   set to false, the callback executes on the worker thread and not on the main
'   UI thread. You can only update a UI component on the thread on which it was
'   created. Refer to the How to: Safely Dispose Task When Using Asynchronous
'   Callbacks topic in the NI-DAQmx .NET help for more information.
'
' I/O Connections Overview:
'   Make sure your signal input terminals match the Physical Channel I/O
'   controls.
'
' Microsoft Windows Vista User Account Control
'   Running certain applications on Microsoft Windows Vista requires
'   administrator privileges, 
'   because the application name contains keywords such as setup, update, or
'   install. To avoid this problem, 
'   you must add an additional manifest to the application that specifies the
'   privileges required to run 
'   the application. Some Measurement Studio NI-DAQmx examples for Visual Studio
'   include these keywords. 
'   Therefore, all examples for Visual Studio are shipped with an additional
'   manifest file that you must 
'   embed in the example executable. The manifest file is named
'   [ExampleName].exe.manifest, where [ExampleName] 
'   is the NI-provided example name. For information on how to embed the manifest
'   file, refer to http://msdn2.microsoft.com/en-us/library/bb756929.aspx.Note: 
'   The manifest file is not provided with examples for Visual Studio .NET 2003.
'
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

Imports System
Imports System.Drawing
Imports System.Collections
Imports System.ComponentModel
Imports System.Windows.Forms
Imports System.Data
Imports NationalInstruments
Imports NationalInstruments.DAQmx

Public Class MainForm
    Inherits System.Windows.Forms.Form
    Private inputDataTable As DataTable = Nothing
    Private inputDataColumns As DataColumn() = Nothing
    Private inputTask As Task
    Private outputTask As Task
    Private reader As AnalogSingleChannelReader
    Private writer As AnalogSingleChannelWriter
    Private inputCallback As AsyncCallback
    Private output() As Double
    Private runningTask As Task

    Friend WithEvents timingGroupBox As System.Windows.Forms.GroupBox
    Friend WithEvents rateNumeric As System.Windows.Forms.NumericUpDown
    Friend WithEvents rateLabel As System.Windows.Forms.Label
    Friend WithEvents startButton As System.Windows.Forms.Button
    Friend WithEvents stopButton As System.Windows.Forms.Button
    Friend WithEvents amplitudeNumeric As System.Windows.Forms.NumericUpDown
    Friend WithEvents waveformTypeLabel As System.Windows.Forms.Label
    Friend WithEvents amplitudeLabel As System.Windows.Forms.Label
    Friend WithEvents waveformGroupBox As System.Windows.Forms.GroupBox
    Friend WithEvents waveformTypeComboBox As System.Windows.Forms.ComboBox
    Friend WithEvents triggerEdgeLabel As System.Windows.Forms.Label
    Friend WithEvents inputChannelComboBox As System.Windows.Forms.ComboBox
    Friend WithEvents inputMinValNumeric As System.Windows.Forms.NumericUpDown
    Friend WithEvents inputChanLabel As System.Windows.Forms.Label
    Friend WithEvents inputMaxValLabel As System.Windows.Forms.Label
    Friend WithEvents inputMinValLabel As System.Windows.Forms.Label
    Friend WithEvents inputMaxValNumeric As System.Windows.Forms.NumericUpDown
    Friend WithEvents samplesLabel As System.Windows.Forms.Label
    Friend WithEvents samplesNumeric As System.Windows.Forms.NumericUpDown
    Friend WithEvents outputChannelComboBox As System.Windows.Forms.ComboBox
    Friend WithEvents outputMinValNumeric As System.Windows.Forms.NumericUpDown
    Friend WithEvents outputMaxValLabel As System.Windows.Forms.Label
    Friend WithEvents outputMinValLabel As System.Windows.Forms.Label
    Friend WithEvents outputMaxValNumeric As System.Windows.Forms.NumericUpDown
    Friend WithEvents outputChanLabel As System.Windows.Forms.Label
    Friend WithEvents inputDataGroupBox As System.Windows.Forms.GroupBox
    Friend WithEvents inputDataGrid As System.Windows.Forms.DataGrid
    Friend WithEvents triggerEdgeComboBox As System.Windows.Forms.ComboBox
    Friend WithEvents inputChanGroupBox As System.Windows.Forms.GroupBox
    Friend WithEvents outputChanGroupBox As System.Windows.Forms.GroupBox
    Friend WithEvents triggerGroupBox As System.Windows.Forms.GroupBox

    Private components As System.ComponentModel.Container = Nothing


    Public Sub New()
        MyBase.New()
        Application.EnableVisualStyles()

        '
        ' Required for Windows Form Designer support
        '
        InitializeComponent()

        ' Initialize UI
        inputChannelComboBox.Items.AddRange(DaqSystem.Local.GetPhysicalChannels(PhysicalChannelTypes.AI, PhysicalChannelAccess.External))
        outputChannelComboBox.Items.AddRange(DaqSystem.Local.GetPhysicalChannels(PhysicalChannelTypes.AO, PhysicalChannelAccess.External))

        waveformTypeComboBox.SelectedIndex = 0
        triggerEdgeComboBox.SelectedIndex = 0

        ' Set up the AI data tables
        inputDataTable = New DataTable

        InitializeDataTables(25)
        inputDataGrid.DataSource = inputDataTable
    End Sub 'New

    Protected Overloads Overrides Sub Dispose(ByVal disposing As Boolean)
        If disposing Then
            If Not (components Is Nothing) Then
                components.Dispose()
            End If
            If Not (inputTask Is Nothing) Then
                runningTask = Nothing
                inputTask.Dispose()
            End If
            If Not (outputTask Is Nothing) Then
                outputTask.Dispose()
            End If
        End If
        MyBase.Dispose(disposing)
    End Sub 'Dispose
    Friend WithEvents frequencyNumeric As System.Windows.Forms.NumericUpDown
    Friend WithEvents frequencyLabel As System.Windows.Forms.Label

    Private Sub InitializeComponent()
        Dim resources As System.Resources.ResourceManager = New System.Resources.ResourceManager(GetType(MainForm))
        Me.inputChanGroupBox = New System.Windows.Forms.GroupBox
        Me.inputChannelComboBox = New System.Windows.Forms.ComboBox
        Me.inputMinValNumeric = New System.Windows.Forms.NumericUpDown
        Me.inputChanLabel = New System.Windows.Forms.Label
        Me.inputMaxValLabel = New System.Windows.Forms.Label
        Me.inputMinValLabel = New System.Windows.Forms.Label
        Me.inputMaxValNumeric = New System.Windows.Forms.NumericUpDown
        Me.timingGroupBox = New System.Windows.Forms.GroupBox
        Me.rateNumeric = New System.Windows.Forms.NumericUpDown
        Me.samplesLabel = New System.Windows.Forms.Label
        Me.rateLabel = New System.Windows.Forms.Label
        Me.samplesNumeric = New System.Windows.Forms.NumericUpDown
        Me.frequencyNumeric = New System.Windows.Forms.NumericUpDown
        Me.frequencyLabel = New System.Windows.Forms.Label
        Me.startButton = New System.Windows.Forms.Button
        Me.outputChanGroupBox = New System.Windows.Forms.GroupBox
        Me.outputChannelComboBox = New System.Windows.Forms.ComboBox
        Me.outputMinValNumeric = New System.Windows.Forms.NumericUpDown
        Me.outputMaxValLabel = New System.Windows.Forms.Label
        Me.outputMinValLabel = New System.Windows.Forms.Label
        Me.outputMaxValNumeric = New System.Windows.Forms.NumericUpDown
        Me.outputChanLabel = New System.Windows.Forms.Label
        Me.stopButton = New System.Windows.Forms.Button
        Me.waveformGroupBox = New System.Windows.Forms.GroupBox
        Me.waveformTypeComboBox = New System.Windows.Forms.ComboBox
        Me.amplitudeNumeric = New System.Windows.Forms.NumericUpDown
        Me.waveformTypeLabel = New System.Windows.Forms.Label
        Me.amplitudeLabel = New System.Windows.Forms.Label
        Me.inputDataGroupBox = New System.Windows.Forms.GroupBox
        Me.inputDataGrid = New System.Windows.Forms.DataGrid
        Me.triggerEdgeLabel = New System.Windows.Forms.Label
        Me.triggerEdgeComboBox = New System.Windows.Forms.ComboBox
        Me.triggerGroupBox = New System.Windows.Forms.GroupBox
        Me.inputChanGroupBox.SuspendLayout()
        CType(Me.inputMinValNumeric, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.inputMaxValNumeric, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.timingGroupBox.SuspendLayout()
        CType(Me.rateNumeric, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.samplesNumeric, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.frequencyNumeric, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.outputChanGroupBox.SuspendLayout()
        CType(Me.outputMinValNumeric, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.outputMaxValNumeric, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.waveformGroupBox.SuspendLayout()
        CType(Me.amplitudeNumeric, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.inputDataGroupBox.SuspendLayout()
        CType(Me.inputDataGrid, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.triggerGroupBox.SuspendLayout()
        Me.SuspendLayout()
        '
        'inputChanGroupBox
        '
        Me.inputChanGroupBox.Controls.Add(Me.inputChannelComboBox)
        Me.inputChanGroupBox.Controls.Add(Me.inputMinValNumeric)
        Me.inputChanGroupBox.Controls.Add(Me.inputChanLabel)
        Me.inputChanGroupBox.Controls.Add(Me.inputMaxValLabel)
        Me.inputChanGroupBox.Controls.Add(Me.inputMinValLabel)
        Me.inputChanGroupBox.Controls.Add(Me.inputMaxValNumeric)
        Me.inputChanGroupBox.FlatStyle = System.Windows.Forms.FlatStyle.System
        Me.inputChanGroupBox.Location = New System.Drawing.Point(8, 8)
        Me.inputChanGroupBox.Name = "inputChanGroupBox"
        Me.inputChanGroupBox.Size = New System.Drawing.Size(328, 112)
        Me.inputChanGroupBox.TabIndex = 0
        Me.inputChanGroupBox.TabStop = False
        Me.inputChanGroupBox.Text = "Channel Parameters - Input"
        '
        'inputChannelComboBox
        '
        Me.inputChannelComboBox.Location = New System.Drawing.Point(152, 24)
        Me.inputChannelComboBox.Name = "inputChannelComboBox"
        Me.inputChannelComboBox.Size = New System.Drawing.Size(168, 21)
        Me.inputChannelComboBox.TabIndex = 1
        Me.inputChannelComboBox.Text = "Dev1/ai0"
        '
        'inputMinValNumeric
        '
        Me.inputMinValNumeric.DecimalPlaces = 2
        Me.inputMinValNumeric.Location = New System.Drawing.Point(152, 80)
        Me.inputMinValNumeric.Minimum = New Decimal(New Integer() {100, 0, 0, -2147483648})
        Me.inputMinValNumeric.Name = "inputMinValNumeric"
        Me.inputMinValNumeric.Size = New System.Drawing.Size(168, 20)
        Me.inputMinValNumeric.TabIndex = 5
        Me.inputMinValNumeric.Value = New Decimal(New Integer() {10, 0, 0, -2147483648})
        '
        'inputChanLabel
        '
        Me.inputChanLabel.FlatStyle = System.Windows.Forms.FlatStyle.System
        Me.inputChanLabel.Location = New System.Drawing.Point(16, 26)
        Me.inputChanLabel.Name = "inputChanLabel"
        Me.inputChanLabel.Size = New System.Drawing.Size(96, 16)
        Me.inputChanLabel.TabIndex = 0
        Me.inputChanLabel.Text = "Input Channel:"
        '
        'inputMaxValLabel
        '
        Me.inputMaxValLabel.FlatStyle = System.Windows.Forms.FlatStyle.System
        Me.inputMaxValLabel.Location = New System.Drawing.Point(16, 54)
        Me.inputMaxValLabel.Name = "inputMaxValLabel"
        Me.inputMaxValLabel.Size = New System.Drawing.Size(96, 16)
        Me.inputMaxValLabel.TabIndex = 2
        Me.inputMaxValLabel.Text = "Maximum Value:"
        '
        'inputMinValLabel
        '
        Me.inputMinValLabel.FlatStyle = System.Windows.Forms.FlatStyle.System
        Me.inputMinValLabel.Location = New System.Drawing.Point(16, 82)
        Me.inputMinValLabel.Name = "inputMinValLabel"
        Me.inputMinValLabel.Size = New System.Drawing.Size(96, 16)
        Me.inputMinValLabel.TabIndex = 4
        Me.inputMinValLabel.Text = "Minimum Value:"
        '
        'inputMaxValNumeric
        '
        Me.inputMaxValNumeric.DecimalPlaces = 2
        Me.inputMaxValNumeric.Location = New System.Drawing.Point(152, 52)
        Me.inputMaxValNumeric.Name = "inputMaxValNumeric"
        Me.inputMaxValNumeric.Size = New System.Drawing.Size(168, 20)
        Me.inputMaxValNumeric.TabIndex = 3
        Me.inputMaxValNumeric.Value = New Decimal(New Integer() {10, 0, 0, 0})
        '
        'timingGroupBox
        '
        Me.timingGroupBox.Controls.Add(Me.rateNumeric)
        Me.timingGroupBox.Controls.Add(Me.samplesLabel)
        Me.timingGroupBox.Controls.Add(Me.rateLabel)
        Me.timingGroupBox.Controls.Add(Me.samplesNumeric)
        Me.timingGroupBox.FlatStyle = System.Windows.Forms.FlatStyle.System
        Me.timingGroupBox.Location = New System.Drawing.Point(8, 248)
        Me.timingGroupBox.Name = "timingGroupBox"
        Me.timingGroupBox.Size = New System.Drawing.Size(328, 88)
        Me.timingGroupBox.TabIndex = 2
        Me.timingGroupBox.TabStop = False
        Me.timingGroupBox.Text = "Timing Parameters"
        '
        'rateNumeric
        '
        Me.rateNumeric.DecimalPlaces = 2
        Me.rateNumeric.Location = New System.Drawing.Point(152, 24)
        Me.rateNumeric.Maximum = New Decimal(New Integer() {102400, 0, 0, 0})
        Me.rateNumeric.Name = "rateNumeric"
        Me.rateNumeric.Size = New System.Drawing.Size(168, 20)
        Me.rateNumeric.TabIndex = 1
        Me.rateNumeric.Value = New Decimal(New Integer() {25, 0, 0, 0})
        '
        'samplesLabel
        '
        Me.samplesLabel.FlatStyle = System.Windows.Forms.FlatStyle.System
        Me.samplesLabel.Location = New System.Drawing.Point(16, 54)
        Me.samplesLabel.Name = "samplesLabel"
        Me.samplesLabel.Size = New System.Drawing.Size(120, 16)
        Me.samplesLabel.TabIndex = 2
        Me.samplesLabel.Text = "Samples:"
        '
        'rateLabel
        '
        Me.rateLabel.FlatStyle = System.Windows.Forms.FlatStyle.System
        Me.rateLabel.Location = New System.Drawing.Point(16, 26)
        Me.rateLabel.Name = "rateLabel"
        Me.rateLabel.Size = New System.Drawing.Size(96, 16)
        Me.rateLabel.TabIndex = 0
        Me.rateLabel.Text = "Sample Rate (Hz):"
        '
        'samplesNumeric
        '
        Me.samplesNumeric.Location = New System.Drawing.Point(152, 52)
        Me.samplesNumeric.Maximum = New Decimal(New Integer() {1000, 0, 0, 0})
        Me.samplesNumeric.Name = "samplesNumeric"
        Me.samplesNumeric.Size = New System.Drawing.Size(168, 20)
        Me.samplesNumeric.TabIndex = 3
        Me.samplesNumeric.Value = New Decimal(New Integer() {25, 0, 0, 0})
        '
        'frequencyNumeric
        '
        Me.frequencyNumeric.DecimalPlaces = 2
        Me.frequencyNumeric.Location = New System.Drawing.Point(152, 52)
        Me.frequencyNumeric.Maximum = New Decimal(New Integer() {102400, 0, 0, 0})
        Me.frequencyNumeric.Name = "frequencyNumeric"
        Me.frequencyNumeric.Size = New System.Drawing.Size(168, 20)
        Me.frequencyNumeric.TabIndex = 3
        Me.frequencyNumeric.Value = New Decimal(New Integer() {1, 0, 0, 0})
        '
        'frequencyLabel
        '
        Me.frequencyLabel.FlatStyle = System.Windows.Forms.FlatStyle.System
        Me.frequencyLabel.Location = New System.Drawing.Point(16, 54)
        Me.frequencyLabel.Name = "frequencyLabel"
        Me.frequencyLabel.Size = New System.Drawing.Size(120, 16)
        Me.frequencyLabel.TabIndex = 2
        Me.frequencyLabel.Text = "Frequency (Hz):"
        '
        'startButton
        '
        Me.startButton.FlatStyle = System.Windows.Forms.FlatStyle.System
        Me.startButton.Location = New System.Drawing.Point(368, 495)
        Me.startButton.Name = "startButton"
        Me.startButton.Size = New System.Drawing.Size(75, 23)
        Me.startButton.TabIndex = 6
        Me.startButton.Text = "Start"
        '
        'outputChanGroupBox
        '
        Me.outputChanGroupBox.Controls.Add(Me.outputChannelComboBox)
        Me.outputChanGroupBox.Controls.Add(Me.outputMinValNumeric)
        Me.outputChanGroupBox.Controls.Add(Me.outputMaxValLabel)
        Me.outputChanGroupBox.Controls.Add(Me.outputMinValLabel)
        Me.outputChanGroupBox.Controls.Add(Me.outputMaxValNumeric)
        Me.outputChanGroupBox.Controls.Add(Me.outputChanLabel)
        Me.outputChanGroupBox.FlatStyle = System.Windows.Forms.FlatStyle.System
        Me.outputChanGroupBox.Location = New System.Drawing.Point(8, 128)
        Me.outputChanGroupBox.Name = "outputChanGroupBox"
        Me.outputChanGroupBox.Size = New System.Drawing.Size(328, 112)
        Me.outputChanGroupBox.TabIndex = 1
        Me.outputChanGroupBox.TabStop = False
        Me.outputChanGroupBox.Text = "Channel Parameters - Output"
        '
        'outputChannelComboBox
        '
        Me.outputChannelComboBox.Location = New System.Drawing.Point(152, 24)
        Me.outputChannelComboBox.Name = "outputChannelComboBox"
        Me.outputChannelComboBox.Size = New System.Drawing.Size(168, 21)
        Me.outputChannelComboBox.TabIndex = 1
        Me.outputChannelComboBox.Text = "Dev1/ao0"
        '
        'outputMinValNumeric
        '
        Me.outputMinValNumeric.DecimalPlaces = 2
        Me.outputMinValNumeric.Location = New System.Drawing.Point(152, 80)
        Me.outputMinValNumeric.Minimum = New Decimal(New Integer() {100, 0, 0, -2147483648})
        Me.outputMinValNumeric.Name = "outputMinValNumeric"
        Me.outputMinValNumeric.Size = New System.Drawing.Size(168, 20)
        Me.outputMinValNumeric.TabIndex = 5
        Me.outputMinValNumeric.Value = New Decimal(New Integer() {10, 0, 0, -2147483648})
        '
        'outputMaxValLabel
        '
        Me.outputMaxValLabel.FlatStyle = System.Windows.Forms.FlatStyle.System
        Me.outputMaxValLabel.Location = New System.Drawing.Point(16, 54)
        Me.outputMaxValLabel.Name = "outputMaxValLabel"
        Me.outputMaxValLabel.Size = New System.Drawing.Size(96, 16)
        Me.outputMaxValLabel.TabIndex = 2
        Me.outputMaxValLabel.Text = "Maximum Value:"
        '
        'outputMinValLabel
        '
        Me.outputMinValLabel.FlatStyle = System.Windows.Forms.FlatStyle.System
        Me.outputMinValLabel.Location = New System.Drawing.Point(16, 82)
        Me.outputMinValLabel.Name = "outputMinValLabel"
        Me.outputMinValLabel.Size = New System.Drawing.Size(96, 16)
        Me.outputMinValLabel.TabIndex = 4
        Me.outputMinValLabel.Text = "Minimum Value:"
        '
        'outputMaxValNumeric
        '
        Me.outputMaxValNumeric.DecimalPlaces = 2
        Me.outputMaxValNumeric.Location = New System.Drawing.Point(152, 52)
        Me.outputMaxValNumeric.Name = "outputMaxValNumeric"
        Me.outputMaxValNumeric.Size = New System.Drawing.Size(168, 20)
        Me.outputMaxValNumeric.TabIndex = 3
        Me.outputMaxValNumeric.Value = New Decimal(New Integer() {10, 0, 0, 0})
        '
        'outputChanLabel
        '
        Me.outputChanLabel.FlatStyle = System.Windows.Forms.FlatStyle.System
        Me.outputChanLabel.Location = New System.Drawing.Point(16, 26)
        Me.outputChanLabel.Name = "outputChanLabel"
        Me.outputChanLabel.Size = New System.Drawing.Size(96, 16)
        Me.outputChanLabel.TabIndex = 0
        Me.outputChanLabel.Text = "Output Channel:"
        '
        'stopButton
        '
        Me.stopButton.Enabled = False
        Me.stopButton.FlatStyle = System.Windows.Forms.FlatStyle.System
        Me.stopButton.Location = New System.Drawing.Point(488, 495)
        Me.stopButton.Name = "stopButton"
        Me.stopButton.Size = New System.Drawing.Size(75, 23)
        Me.stopButton.TabIndex = 7
        Me.stopButton.Text = "Stop"
        '
        'waveformGroupBox
        '
        Me.waveformGroupBox.Controls.Add(Me.waveformTypeComboBox)
        Me.waveformGroupBox.Controls.Add(Me.amplitudeNumeric)
        Me.waveformGroupBox.Controls.Add(Me.waveformTypeLabel)
        Me.waveformGroupBox.Controls.Add(Me.amplitudeLabel)
        Me.waveformGroupBox.Controls.Add(Me.frequencyLabel)
        Me.waveformGroupBox.Controls.Add(Me.frequencyNumeric)
        Me.waveformGroupBox.FlatStyle = System.Windows.Forms.FlatStyle.System
        Me.waveformGroupBox.Location = New System.Drawing.Point(8, 406)
        Me.waveformGroupBox.Name = "waveformGroupBox"
        Me.waveformGroupBox.Size = New System.Drawing.Size(328, 112)
        Me.waveformGroupBox.TabIndex = 4
        Me.waveformGroupBox.TabStop = False
        Me.waveformGroupBox.Text = "Waveform Parameters"
        '
        'waveformTypeComboBox
        '
        Me.waveformTypeComboBox.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList
        Me.waveformTypeComboBox.Items.AddRange(New Object() {"Sine"})
        Me.waveformTypeComboBox.Location = New System.Drawing.Point(152, 24)
        Me.waveformTypeComboBox.Name = "waveformTypeComboBox"
        Me.waveformTypeComboBox.Size = New System.Drawing.Size(168, 21)
        Me.waveformTypeComboBox.TabIndex = 1
        '
        'amplitudeNumeric
        '
        Me.amplitudeNumeric.DecimalPlaces = 3
        Me.amplitudeNumeric.Location = New System.Drawing.Point(152, 80)
        Me.amplitudeNumeric.Maximum = New Decimal(New Integer() {102400, 0, 0, 0})
        Me.amplitudeNumeric.Name = "amplitudeNumeric"
        Me.amplitudeNumeric.Size = New System.Drawing.Size(168, 20)
        Me.amplitudeNumeric.TabIndex = 5
        Me.amplitudeNumeric.Value = New Decimal(New Integer() {1, 0, 0, 0})
        '
        'waveformTypeLabel
        '
        Me.waveformTypeLabel.FlatStyle = System.Windows.Forms.FlatStyle.System
        Me.waveformTypeLabel.Location = New System.Drawing.Point(16, 26)
        Me.waveformTypeLabel.Name = "waveformTypeLabel"
        Me.waveformTypeLabel.Size = New System.Drawing.Size(96, 16)
        Me.waveformTypeLabel.TabIndex = 0
        Me.waveformTypeLabel.Text = "Waveform Type:"
        '
        'amplitudeLabel
        '
        Me.amplitudeLabel.FlatStyle = System.Windows.Forms.FlatStyle.System
        Me.amplitudeLabel.Location = New System.Drawing.Point(16, 82)
        Me.amplitudeLabel.Name = "amplitudeLabel"
        Me.amplitudeLabel.Size = New System.Drawing.Size(96, 16)
        Me.amplitudeLabel.TabIndex = 4
        Me.amplitudeLabel.Text = "Amplitude:"
        '
        'inputDataGroupBox
        '
        Me.inputDataGroupBox.Controls.Add(Me.inputDataGrid)
        Me.inputDataGroupBox.FlatStyle = System.Windows.Forms.FlatStyle.System
        Me.inputDataGroupBox.Location = New System.Drawing.Point(344, 8)
        Me.inputDataGroupBox.Name = "inputDataGroupBox"
        Me.inputDataGroupBox.Size = New System.Drawing.Size(254, 471)
        Me.inputDataGroupBox.TabIndex = 5
        Me.inputDataGroupBox.TabStop = False
        Me.inputDataGroupBox.Text = "Input Data"
        '
        'inputDataGrid
        '
        Me.inputDataGrid.AllowSorting = False
        Me.inputDataGrid.DataMember = ""
        Me.inputDataGrid.HeaderForeColor = System.Drawing.SystemColors.ControlText
        Me.inputDataGrid.Location = New System.Drawing.Point(3, 16)
        Me.inputDataGrid.Name = "inputDataGrid"
        Me.inputDataGrid.PreferredColumnWidth = 150
        Me.inputDataGrid.ReadOnly = True
        Me.inputDataGrid.Size = New System.Drawing.Size(245, 449)
        Me.inputDataGrid.TabIndex = 0
        Me.inputDataGrid.TabStop = False
        '
        'triggerEdgeLabel
        '
        Me.triggerEdgeLabel.FlatStyle = System.Windows.Forms.FlatStyle.System
        Me.triggerEdgeLabel.Location = New System.Drawing.Point(16, 21)
        Me.triggerEdgeLabel.Name = "triggerEdgeLabel"
        Me.triggerEdgeLabel.Size = New System.Drawing.Size(96, 16)
        Me.triggerEdgeLabel.TabIndex = 2
        Me.triggerEdgeLabel.Text = "Trigger Edge:"
        '
        'triggerEdgeComboBox
        '
        Me.triggerEdgeComboBox.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList
        Me.triggerEdgeComboBox.Items.AddRange(New Object() {"Rising", "Falling"})
        Me.triggerEdgeComboBox.Location = New System.Drawing.Point(152, 19)
        Me.triggerEdgeComboBox.Name = "triggerEdgeComboBox"
        Me.triggerEdgeComboBox.Size = New System.Drawing.Size(168, 21)
        Me.triggerEdgeComboBox.TabIndex = 3
        '
        'triggerGroupBox
        '
        Me.triggerGroupBox.Controls.Add(Me.triggerEdgeLabel)
        Me.triggerGroupBox.Controls.Add(Me.triggerEdgeComboBox)
        Me.triggerGroupBox.FlatStyle = System.Windows.Forms.FlatStyle.System
        Me.triggerGroupBox.Location = New System.Drawing.Point(8, 344)
        Me.triggerGroupBox.Name = "triggerGroupBox"
        Me.triggerGroupBox.Size = New System.Drawing.Size(328, 52)
        Me.triggerGroupBox.TabIndex = 3
        Me.triggerGroupBox.TabStop = False
        Me.triggerGroupBox.Text = "Trigger Parameters"
        '
        'MainForm
        '
        Me.AutoScaleBaseSize = New System.Drawing.Size(5, 13)
        Me.ClientSize = New System.Drawing.Size(610, 525)
        Me.Controls.Add(Me.inputDataGroupBox)
        Me.Controls.Add(Me.startButton)
        Me.Controls.Add(Me.inputChanGroupBox)
        Me.Controls.Add(Me.timingGroupBox)
        Me.Controls.Add(Me.outputChanGroupBox)
        Me.Controls.Add(Me.stopButton)
        Me.Controls.Add(Me.waveformGroupBox)
        Me.Controls.Add(Me.triggerGroupBox)
        Me.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog
        Me.Icon = CType(resources.GetObject("$this.Icon"), System.Drawing.Icon)
        Me.MaximizeBox = False
        Me.Name = "MainForm"
        Me.Text = "MultiFunction Sync - AI and AO - External Start Trigger"
        Me.inputChanGroupBox.ResumeLayout(False)
        CType(Me.inputMinValNumeric, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.inputMaxValNumeric, System.ComponentModel.ISupportInitialize).EndInit()
        Me.timingGroupBox.ResumeLayout(False)
        CType(Me.rateNumeric, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.samplesNumeric, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.frequencyNumeric, System.ComponentModel.ISupportInitialize).EndInit()
        Me.outputChanGroupBox.ResumeLayout(False)
        CType(Me.outputMinValNumeric, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.outputMaxValNumeric, System.ComponentModel.ISupportInitialize).EndInit()
        Me.waveformGroupBox.ResumeLayout(False)
        CType(Me.amplitudeNumeric, System.ComponentModel.ISupportInitialize).EndInit()
        Me.inputDataGroupBox.ResumeLayout(False)
        CType(Me.inputDataGrid, System.ComponentModel.ISupportInitialize).EndInit()
        Me.triggerGroupBox.ResumeLayout(False)
        Me.ResumeLayout(False)

    End Sub 'InitializeComponent

    Private Overloads Sub ConfigNumeric(ByVal numeric As NumericUpDown, ByVal minVal As Decimal)
        numeric.Minimum = minVal
        numeric.Maximum = [Decimal].MaxValue
    End Sub 'ConfigNumeric

    Private Overloads Sub ConfigNumeric(ByVal numeric As NumericUpDown)
        ConfigNumeric(numeric, [Decimal].MinValue)
    End Sub 'ConfigNumeric

    Private Sub InitializeDataTables(ByVal rows As Integer)
        ' Clear out the data
        inputDataTable.Rows.Clear()

        inputDataTable.Columns.Clear()

        ' Add one column to each DataGrid of type double
        inputDataColumns = New DataColumn(1) {}

        inputDataColumns(0) = New DataColumn
        inputDataColumns(0).DataType = GetType(Double)
        inputDataColumns(0).ColumnName = "Input Data"

        inputDataTable.Columns.AddRange(inputDataColumns)

        ' Now add a certain number of rows
        Dim i As Integer
        For i = 0 To rows - 1
            Dim rowArr(0) As Object
            inputDataTable.Rows.Add(rowArr)
        Next i
    End Sub 'InitializeDataTables


    Private Sub startButton_Click(ByVal sender As Object, ByVal e As System.EventArgs) Handles startButton.Click
        ' Change the mouse to an hourglass for the duration of this function.
        System.Windows.Forms.Cursor.Current = Cursors.WaitCursor

        ' Read UI selections
        Dim triggerEdge As DigitalEdgeStartTriggerEdge
        If Me.triggerEdgeComboBox.Text = "Rising" Then
            triggerEdge = DigitalEdgeStartTriggerEdge.Rising
        Else
            triggerEdge = DigitalEdgeStartTriggerEdge.Falling
        End If

        Try
            ' Create the master and slave tasks
            inputTask = New Task("inputTask")
            outputTask = New Task("outputTask")

            ' Configure both tasks with the values selected on the UI.
            inputTask.AIChannels.CreateVoltageChannel(inputChannelComboBox.Text, "", AITerminalConfiguration.Differential, Convert.ToDouble(inputMinValNumeric.Value), Convert.ToDouble(inputMaxValNumeric.Value), AIVoltageUnits.Volts)

            outputTask.AOChannels.CreateVoltageChannel(outputChannelComboBox.Text, "", Convert.ToDouble(outputMinValNumeric.Value), Convert.ToDouble(outputMaxValNumeric.Value), AOVoltageUnits.Volts)

            ' Set up the timing
            inputTask.Timing.ConfigureSampleClock("", Convert.ToDouble(rateNumeric.Value), SampleClockActiveEdge.Rising, SampleQuantityMode.ContinuousSamples, Convert.ToInt32(samplesNumeric.Value))

            outputTask.Timing.ConfigureSampleClock("", Convert.ToDouble(rateNumeric.Value), SampleClockActiveEdge.Rising, SampleQuantityMode.ContinuousSamples, Convert.ToInt32(samplesNumeric.Value))

            ' Set up the start trigger
            Dim deviceName As String = inputChannelComboBox.Text.Split("/"c)(0)
            Dim terminalNameBase As String = "/" + GetDeviceName(deviceName) + "/"
            outputTask.Triggers.StartTrigger.ConfigureDigitalEdgeTrigger(terminalNameBase + "ai/StartTrigger", triggerEdge)

            ' Verify the tasks
            inputTask.Control(TaskAction.Verify)
            outputTask.Control(TaskAction.Verify)

            ' Write data to each output channel
            Dim fGen As New NationalInstruments.Examples.FunctionGenerator(Convert.ToString(frequencyNumeric.Value), _
                samplesNumeric.Value.ToString(), _
                Convert.ToString(frequencyNumeric.Value / (rateNumeric.Value / samplesNumeric.Value)), _
                waveformTypeComboBox.Text, _
                amplitudeNumeric.Value.ToString())

            output = fGen.Data

            writer = New AnalogSingleChannelWriter(outputTask.Stream)
            writer.WriteMultiSample(False, output)

            ' Officially start the task
            StartTask()

            outputTask.Start()
            inputTask.Start()

            ' Start reading as well
            inputCallback = New AsyncCallback(AddressOf InputRead)
            reader = New AnalogSingleChannelReader(inputTask.Stream)

            ' Use SynchronizeCallbacks to specify that the object 
            ' marshals callbacks across threads appropriately.
            reader.SynchronizeCallbacks = True

            reader.BeginReadMultiSample(Convert.ToInt32(samplesNumeric.Value), inputCallback, inputTask)
        Catch ex As Exception
            StopTask()
            MessageBox.Show(ex.Message)
        End Try
    End Sub 'startButton_Click


    Private Sub InputRead(ByVal ar As IAsyncResult)
        Try
            If (Not (runningTask Is Nothing)) AndAlso runningTask Is ar.AsyncState Then
                ' Read the data
                Dim data As Double() = reader.EndReadMultiSample(ar)

                ' Display the data
                Dim i As Integer
                While i < inputDataTable.Rows.Count And i < data.Length
                    inputDataTable.Rows(i)(0) = data(i)
                    i = i + 1
                End While

                For i = data.Length To inputDataTable.Rows.Count - 1
                    inputDataTable.Rows(i)(0) = DBNull.Value
                Next

                ' Set up next callback
                reader.BeginReadMultiSample(Convert.ToInt32(samplesNumeric.Value), inputCallback, inputTask)
            End If
        Catch ex As Exception
            StopTask()
            MessageBox.Show(ex.Message)
        End Try
    End Sub 'InputRead


    Private Sub stopButton_Click(ByVal sender As Object, ByVal e As System.EventArgs) Handles stopButton.Click
        StopTask()
    End Sub 'stopButton_Click


    Private Sub StartTask()
        If runningTask Is Nothing Then
            ' Change state
            runningTask = inputTask

            ' Fix UI
            inputChannelComboBox.Enabled = False
            inputMinValNumeric.Enabled = False
            inputMaxValNumeric.Enabled = False

            outputChannelComboBox.Enabled = False
            outputChannelComboBox.Enabled = False
            outputChannelComboBox.Enabled = False
            outputMaxValNumeric.Enabled = False
            outputMinValNumeric.Enabled = False

            rateNumeric.Enabled = False
            frequencyNumeric.Enabled = False
            samplesNumeric.Enabled = False

            waveformTypeComboBox.Enabled = False
            amplitudeNumeric.Enabled = False
            triggerEdgeComboBox.Enabled = False

            startButton.Enabled = False
            stopButton.Enabled = True
        End If
    End Sub 'StartTask


    Private Sub StopTask()
        ' Change state
        runningTask = Nothing

        ' Fix UI
        inputChannelComboBox.Enabled = True
        inputMinValNumeric.Enabled = True
        inputMaxValNumeric.Enabled = True

        outputChannelComboBox.Enabled = True
        outputChannelComboBox.Enabled = True
        outputChannelComboBox.Enabled = True
        outputMaxValNumeric.Enabled = True
        outputMinValNumeric.Enabled = True

        rateNumeric.Enabled = True
        frequencyNumeric.Enabled = True
        samplesNumeric.Enabled = True

        waveformTypeComboBox.Enabled = True
        amplitudeNumeric.Enabled = True
        triggerEdgeComboBox.Enabled = True

        startButton.Enabled = True
        stopButton.Enabled = False

        ' Stop tasks
        inputTask.Stop()
        outputTask.Stop()

        inputTask.Dispose()
        outputTask.Dispose()
    End Sub 'StopTask

    Private Function GetDeviceName(ByVal deviceName As String) As String
        Dim device As Device = DaqSystem.Local.LoadDevice(deviceName)
        If (device.BusType <> DeviceBusType.CompactDaq) Then
            Return deviceName
        Else
            Return device.CompactDaqChassisDeviceName
        End If
    End Function 'GetDeviceName

End Class 'MainForm

